### ISSUE TITLE
404 Download Links

### ISSUE THREAD

**Issue by nguyen-tran** [UCSolarCarTeam/Development-Resources#57]
Direct linking to a specific SourceForge server is generally a bad idea as files are sometimes moved to another server and as a result the page returns 404 like in this scenario:
https://github.com/UCSolarCarTeam/Recruit-Resources/blob/ae096ce0fb3b5420d9a6d1d964f17572e3fe4307/SetupScript/UCSolarTeamInit.sh#L79

wget automatically follows redirects, so a good way to avoid this is to just link to the download page that automatically selects the closest server:
`sudo wget -q https://downloads.sourceforge.net/project/qwt/qwt/6.1.3/qwt-6.1.3.tar.bz2`

**Comment by bill-luu** [comment]
Oh, thanks for the catch! This script hasn't actually been updated in a while, so we'll have to do that.

**Comment by enochtsang** [comment]
@nguyen-tran we keep an s3 bucket, we could optionally host it there as well. Ask bill for credentials, if you want to try that.
