### ISSUE TITLE
Clarity on functions

### ISSUE THREAD

**Issue by nathanaelhuh** [UCSolarCarTeam/Development-Resources#96]
Every year there are lots of people confused as to how to go about doing the recruit training and understanding what actually needs to be done/ what the goal of the function is. 

I think to solve this we need to make the instructions more clear as well as give some explanation/diagram around how the BMS should work etc.

**Comment by bill-luu** [comment]
> I think to solve this we need to make the instructions more clear as well as give some explanation/diagram around how the BMS should work etc.

Are you talking about the real BMS or the BMS in the project?

**Comment by Reddragoneer1** [comment]
BMS in the project
